-- VHDL Entity ece411.aMULTDIV.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 17:02:27 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY aMULTDIV IS
   PORT( 
      ALUop                : IN     lc3b_aluop;
      MULTDIVEN_L_from_cw2 : IN     std_logic;
      MultDivout           : OUT    lc3b_word;
      regA2out             : IN     lc3b_word;
      sourceB              : IN     lc3b_word;
      STALL_ALU_L          : OUT    std_logic
   );

END aMULTDIV ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF aMULTDIV IS 
BEGIN


END generatedInstance;
