-- VHDL Entity ece411.BranchAdd.generatedInstance
--
-- Created:
--          by - adalton2.ews (siebl-0220-12.ews.illinois.edu)
--          at - 21:20:03 04/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BranchAdd IS
   PORT( 
      ADJ9out : IN     LC3b_word;
      calcPC  : OUT    lc3b_word;
      clk     : IN     std_logic;
      PC1out  : IN     lc3b_word
   );

END BranchAdd ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BranchAdd IS 
BEGIN


END generatedInstance;
