-- VHDL Entity ece411.byte_splitter1.generatedInstance
--
-- Created:
--          by - buris2.ews (siebl-0222-02.ews.illinois.edu)
--          at - 01:58:05 04/30/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY byte_splitter1 IS
   PORT( 
      A                : OUT    std_logic;
      B                : OUT    std_logic;
      C                : OUT    std_logic;
      D                : OUT    std_logic;
      E                : OUT    std_logic;
      F                : OUT    std_logic;
      G                : OUT    std_logic;
      H                : OUT    std_logic;
      intersectionMask : IN     lc3b_byte
   );

END byte_splitter1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF byte_splitter1 IS 
BEGIN


END generatedInstance;
