-- VHDL Entity ece411.byteSelect.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-21.ews.illinois.edu)
--          at - 21:36:30 02/06/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY byteSelect IS
   PORT( 
      B_op      : IN     std_logic;
      clk       : IN     std_logic;
      m_align   : IN     std_logic;
      REGDATAin : OUT    LC3b_word;
      RFMuxout  : IN     LC3b_word
   );

END byteSelect ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF byteSelect IS 
BEGIN


END generatedInstance;
