-- VHDL Entity ece411.Cache_Controller.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-17.ews.illinois.edu)
--          at - 21:53:11 02/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Cache_Controller IS
   PORT( 
      clk       : IN     std_logic;
      PMREAD_L  : OUT    STD_LOGIC;
      PMRESP_H  : IN     STD_LOGIC;
      PMWRITE_L : OUT    STD_LOGIC;
      RESET_L   : IN     std_logic;
      set_dirty : OUT    std_logic
   );

END Cache_Controller ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Cache_Controller IS 
BEGIN


END generatedInstance;
