-- VHDL Entity ece411.CROM1.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 21:57:07 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CROM1 IS
   PORT( 
      clk         : IN     std_logic;
      ControlWord : OUT    lc3b_oword;
      opcode      : IN     lc3b_opcode;
      STALL_L     : IN     std_logic
   );

END CROM1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF CROM1 IS 
BEGIN


END generatedInstance;
