-- VHDL Entity ece411.DECODE.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 15:06:50 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DECODE IS
   PORT( 
      clk     : IN     std_logic;
      CW1     : IN     std_logic;
      CW2     : OUT    std_logic;
      IR1     : IN     lc3b_word;
      IR2     : OUT    lc3b_word;
      PC1     : IN     lc3b_word;
      PC2     : OUT    lc3b_word;
      RegA2   : OUT    lc3b_word;
      RegB2   : OUT    lc3b_word;
      RESET_L : IN     std_logic;
      STALL   : IN     std_logic;
      V1      : IN     std_logic;
      V2      : OUT    std_logic
   );

END DECODE ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF DECODE IS 
BEGIN


END generatedInstance;
