-- VHDL Entity ece411.DestReg_MaskCalc.symbol
--
-- Created:
--          by - adalton2.ews (gelib-057-33.ews.illinois.edu)
--          at - 00:49:47 04/18/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DestReg_MaskCalc IS
   PORT( 
      WR_CW    : IN     lc3b_dword;
      WR_IR    : IN     lc3b_word;
      WR_V     : IN     std_logic;
      DestMask : OUT    lc3b_byte
   );

-- Declarations

END DestReg_MaskCalc ;

--
-- VHDL Architecture ece411.DestReg_MaskCalc.struct
--
-- Created:
--          by - adalton2.ews (gelib-057-33.ews.illinois.edu)
--          at - 00:49:47 04/18/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF DestReg_MaskCalc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F              : LC3B_BYTE;
   SIGNAL Valid_delayed  : std_logic;
   SIGNAL Valid_expanded : lc3b_byte;
   SIGNAL dest_used      : std_logic;
   SIGNAL destreg        : lc3b_reg;


   -- Component Declarations
   COMPONENT AND2_byte
   PORT (
      A : IN     lc3b_byte;
      B : IN     lc3b_byte;
      C : OUT    lc3b_byte
   );
   END COMPONENT;
   COMPONENT DeMUX3_8
   PORT (
      A  : IN     lc3b_reg ;
      EN : IN     std_logic ;
      F  : OUT    LC3B_BYTE 
   );
   END COMPONENT;
   COMPONENT WR_CW_ripper
   PORT (
      WR_CW     : IN     lc3b_dword ;
      dest_used : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT WR_IR_ripper
   PORT (
      WR_IR   : IN     lc3b_word ;
      destreg : OUT    lc3b_reg 
   );
   END COMPONENT;
   COMPONENT bit_to_byte
   PORT (
      Valid          : IN     std_logic;
      Valid_expanded : OUT    lc3b_byte
   );
   END COMPONENT;
   COMPONENT valid_delay_4ns
   PORT (
      WR_V          : IN     std_logic ;
      Valid_delayed : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2_byte USE ENTITY ece411.AND2_byte;
   FOR ALL : DeMUX3_8 USE ENTITY ece411.DeMUX3_8;
   FOR ALL : WR_CW_ripper USE ENTITY ece411.WR_CW_ripper;
   FOR ALL : WR_IR_ripper USE ENTITY ece411.WR_IR_ripper;
   FOR ALL : bit_to_byte USE ENTITY ece411.bit_to_byte;
   FOR ALL : valid_delay_4ns USE ENTITY ece411.valid_delay_4ns;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : AND2_byte
      PORT MAP (
         A => F,
         B => Valid_expanded,
         C => DestMask
      );
   U_2 : DeMUX3_8
      PORT MAP (
         A  => destreg,
         EN => dest_used,
         F  => F
      );
   U_0 : WR_CW_ripper
      PORT MAP (
         WR_CW     => WR_CW,
         dest_used => dest_used
      );
   U_1 : WR_IR_ripper
      PORT MAP (
         WR_IR   => WR_IR,
         destreg => destreg
      );
   U_3 : bit_to_byte
      PORT MAP (
         Valid          => Valid_delayed,
         Valid_expanded => Valid_expanded
      );
   U_5 : valid_delay_4ns
      PORT MAP (
         WR_V          => WR_V,
         Valid_delayed => Valid_delayed
      );

END struct;
