-- VHDL Entity ece411.eq_v0Delay6ns.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-33.ews.illinois.edu)
--          at - 12:33:40 02/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY eq_v0Delay6ns IS
   PORT( 
      eq_v0         : IN     std_logic;
      eq_v0_delayed : OUT    std_logic
   );

END eq_v0Delay6ns ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF eq_v0Delay6ns IS 
BEGIN


END generatedInstance;
