-- VHDL Entity ece411.EXECUTE.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 15:06:50 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EXECUTE IS
   PORT( 
      ALUout3 : OUT    lc3b_word;
      clk     : IN     std_logic;
      CW2     : IN     std_logic;
      CW3     : OUT    std_logic;
      IR2     : IN     lc3b_word;
      IR3     : OUT    lc3b_word;
      PC2     : IN     lc3b_word;
      PC3     : OUT    lc3b_word;
      RegA2   : IN     lc3b_word;
      RegA3   : OUT    lc3b_word;
      RegB2   : IN     lc3b_word;
      RegB3   : OUT    lc3b_word;
      RESET_L : IN     std_logic;
      STALL   : IN     std_logic;
      V2      : IN     std_logic;
      V3      : OUT    std_logic
   );

END EXECUTE ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF EXECUTE IS 
BEGIN


END generatedInstance;
