-- VHDL Entity ece411.IR2sig_ripper.generatedInstance
--
-- Created:
--          by - adalton2.ews (siebl-0220-12.ews.illinois.edu)
--          at - 21:20:03 04/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IR2sig_ripper IS
   PORT( 
      imm4   : OUT    lc3b_nibble;
      imm5   : OUT    LC3b_imm5;
      index6 : OUT    LC3b_index6;
      IR2_5  : OUT    std_logic;
      IR2out : IN     lc3b_word
   );

END IR2sig_ripper ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IR2sig_ripper IS 
BEGIN


END generatedInstance;
