-- VHDL Entity ece411.IR3sigripper.generatedInstance
--
-- Created:
--          by - adalton2.ews (siebl-0220-18.ews.illinois.edu)
--          at - 04:02:30 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IR3sigripper IS
   PORT( 
      IR11     : OUT    std_logic;
      IR3out   : IN     lc3b_word;
      IR8      : OUT    std_logic;
      OFFSET11 : OUT    lc3b_OFFSET11;
      OFFSET9  : OUT    LC3B_OFFSET9
   );

END IR3sigripper ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IR3sigripper IS 
BEGIN


END generatedInstance;
