-- VHDL Entity ece411.IRdest_ripper.generatedInstance
--
-- Created:
--          by - adalton2.ews (gelib-057-27.ews.illinois.edu)
--          at - 22:43:32 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IRdest_ripper IS
   PORT( 
      clk      : IN     std_logic;
      destreg5 : OUT    lc3b_reg;
      IR4out   : IN     lc3b_word
   );

END IRdest_ripper ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IRdest_ripper IS 
BEGIN


END generatedInstance;
