-- VHDL Entity ece411.MEM.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 15:06:50 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MEM IS
   PORT( 
      ADDRESS_D : OUT    lc3b_word;
      ALUout3   : IN     lc3b_word;
      ALUout4   : OUT    lc3b_word;
      clk       : IN     std_logic;
      CW3       : IN     std_logic;
      CW4       : OUT    std_logic;
      DATAIN_D  : IN     lc3b_word;
      IR3       : IN     lc3b_word;
      IR4       : OUT    lc3b_word;
      MemData4  : OUT    lc3b_word;
      MREADD_L  : OUT    std_logic;
      MWRITEH_L : OUT    std_logic;
      MWRITEL_L : OUT    std_logic;
      PC3       : IN     lc3b_word;
      PC4       : OUT    lc3b_word;
      RegA3     : IN     lc3b_word;
      RegA4     : OUT    lc3b_word;
      RegB3     : IN     lc3b_word;
      RegB4     : OUT    lc3b_word;
      RESET_L   : IN     std_logic;
      STALL     : IN     std_logic;
      V3        : IN     std_logic;
      V4        : OUT    std_logic
   );

END MEM ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MEM IS 
BEGIN


END generatedInstance;
