-- VHDL Entity ece411.OWord_split.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-17.ews.illinois.edu)
--          at - 21:48:30 02/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY OWord_split IS
   PORT( 
      PMDATAOUT : IN     LC3B_OWORD;
      word0     : OUT    LC3B_WORD;
      word1     : OUT    LC3B_WORD;
      word2     : OUT    LC3B_WORD;
      word3     : OUT    LC3B_WORD;
      word4     : OUT    LC3B_WORD;
      word5     : OUT    LC3B_WORD;
      word6     : OUT    LC3B_WORD;
      word7     : OUT    LC3B_WORD
   );

END OWord_split ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF OWord_split IS 
BEGIN


END generatedInstance;
