-- VHDL Entity ece411.SEXT6.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-21.ews.illinois.edu)
--          at - 21:36:30 02/06/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY SEXT6 IS
   PORT( 
      clk         : IN     std_logic;
      index6      : IN     LC3b_index6;
      SEXToffset6 : OUT    lc3b_word
   );

END SEXT6 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF SEXT6 IS 
BEGIN


END generatedInstance;
