-- VHDL Entity ece411.stage_writeback.symbol
--
-- Created:
--          by - buris2.ews (evrt-252-17.ews.illinois.edu)
--          at - 16:34:08 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY stage_writeback IS
   PORT( 
      ALU4out     : IN     lc3b_word;
      CW4out      : IN     lc3b_dword;
      IR4out      : IN     lc3b_word;
      MEMdata4out : IN     lc3b_word;
      PC4out      : IN     lc3b_word;
      RESET_L     : IN     std_logic;
      STALL_L     : IN     std_logic;
      Valid4out   : IN     std_logic;
      clearValid5 : IN     std_logic;
      clk         : IN     std_logic;
      regA4out    : IN     lc3b_word;
      regB4out    : IN     lc3b_word;
      RegWrite5   : OUT    std_logic;
      destreg5    : OUT    lc3b_reg;
      destsel5    : OUT    std_logic;
      regdata5in  : OUT    lc3b_word
   );

-- Declarations

END stage_writeback ;

--
-- VHDL Architecture ece411.stage_writeback.struct
--
-- Created:
--          by - buris2.ews (evrt-252-17.ews.illinois.edu)
--          at - 16:34:09 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF stage_writeback IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL PC5out           : lc3b_word;
   SIGNAL RegDataInSel     : std_logic;
   SIGNAL RegWrite         : std_logic;
   SIGNAL preregdata       : LC3b_word;
   SIGNAL realAddressplus2 : LC3b_word;
   SIGNAL savePC           : std_logic;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      C : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT CW4sig_ripper
   PORT (
      CW4out       : IN     lc3b_dword ;
      clk          : IN     std_logic ;
      RegDataInSel : OUT    std_logic ;
      RegWrite     : OUT    std_logic ;
      savePC       : OUT    std_logic ;
      destsel5     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT IRdest_ripper
   PORT (
      IR4out   : IN     lc3b_word ;
      clk      : IN     std_logic ;
      destreg5 : OUT    lc3b_reg 
   );
   END COMPONENT;
   COMPONENT Plus2
   PORT (
      PCout      : IN     LC3b_word;
      clk        : IN     std_logic;
      PCPlus2out : OUT    LC3b_word
   );
   END COMPONENT;
   COMPONENT WordMux2
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      Sel : IN     std_logic ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT REG16
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC_VECTOR (15 DOWNTO 0);
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : CW4sig_ripper USE ENTITY ece411.CW4sig_ripper;
   FOR ALL : IRdest_ripper USE ENTITY ece411.IRdest_ripper;
   FOR ALL : Plus2 USE ENTITY ece411.Plus2;
   FOR ALL : REG16 USE ENTITY mp3lib.REG16;
   FOR ALL : WordMux2 USE ENTITY ece411.WordMux2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : AND2
      PORT MAP (
         A => RegWrite,
         B => Valid4out,
         C => RegWrite5
      );
   aCW4sig_ripper : CW4sig_ripper
      PORT MAP (
         CW4out       => CW4out,
         clk          => clk,
         RegDataInSel => RegDataInSel,
         RegWrite     => RegWrite,
         savePC       => savePC,
         destsel5     => destsel5
      );
   aIRdest_ripper : IRdest_ripper
      PORT MAP (
         IR4out   => IR4out,
         clk      => clk,
         destreg5 => destreg5
      );
   U_1 : Plus2
      PORT MAP (
         PCout      => PC5out,
         clk        => clk,
         PCPlus2out => realAddressplus2
      );
   RegDataInMUX : WordMux2
      PORT MAP (
         A   => ALU4out,
         B   => MEMdata4out,
         Sel => RegDataInSel,
         F   => preregdata
      );
   RegDataInMUX1 : WordMux2
      PORT MAP (
         A   => preregdata,
         B   => realAddressplus2,
         Sel => savePC,
         F   => regdata5in
      );
   U_11 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => PC4out,
         EN      => STALL_L,
         CLK     => clk,
         F       => PC5out
      );

END struct;
