-- VHDL Entity ece411.stall_logic.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 15:06:50 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY stall_logic IS
   PORT( 
      clk   : IN     std_logic;
      STALL : OUT    std_logic
   );

END stall_logic ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF stall_logic IS 
BEGIN


END generatedInstance;
