-- VHDL Entity ece411.tagDelay20ns.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-33.ews.illinois.edu)
--          at - 12:33:40 02/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY tagDelay20ns IS
   PORT( 
      tag         : IN     lc3b_c_tag;
      tag_delayed : OUT    lc3b_c_tag
   );

END tagDelay20ns ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF tagDelay20ns IS 
BEGIN


END generatedInstance;
