-- VHDL Entity ece411.Valid1.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 17:02:27 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Valid1 IS
   PORT( 
      clearValid : IN     std_logic;
      clk        : IN     std_logic;
      RESET_L    : IN     std_logic;
      STALL_L    : IN     std_logic;
      Valid1out  : OUT    std_logic
   );

END Valid1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Valid1 IS 
BEGIN


END generatedInstance;
