-- VHDL Entity ece411.Way.symbol
--
-- Created:
--          by - buris2.ews (evrt-252-10.ews.illinois.edu)
--          at - 15:10:18 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Way IS
   PORT( 
      DataIn    : IN     LC3B_OWORD;
      RESET_L   : IN     std_logic;
      set_dirty : IN     std_logic;
      set_index : IN     lc3b_c_index;
      tag       : IN     lc3b_c_tag;
      way_write : IN     std_logic;
      Data_out  : OUT    LC3B_OWORD;
      Dirty_out : OUT    std_logic;
      Tag_out   : OUT    lc3b_c_tag;
      Valid_out : OUT    std_logic
   );

-- Declarations

END Way ;

--
-- VHDL Architecture ece411.Way.struct
--
-- Created:
--          by - buris2.ews (evrt-252-10.ews.illinois.edu)
--          at - 15:10:18 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF Way IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dirty_delayed : std_logic;
   SIGNAL valid         : std_logic;
   SIGNAL write_valid   : std_logic;


   -- Component Declarations
   COMPONENT BitArray
   PORT (
      DataIn    : IN     std_logic;
      DataWrite : IN     std_logic;
      Index     : IN     LC3B_C_INDEX;
      Reset_L   : IN     std_logic;
      DataOut   : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT DataArray
   PORT (
      DataIn    : IN     LC3B_OWORD;
      DataWrite : IN     std_logic;
      Index     : IN     LC3B_C_INDEX;
      Reset_L   : IN     std_logic;
      DataOut   : OUT    LC3B_OWORD
   );
   END COMPONENT;
   COMPONENT TagArray
   PORT (
      DataIn    : IN     LC3B_C_TAG;
      DataWrite : IN     std_logic;
      Index     : IN     LC3B_C_INDEX;
      Reset_L   : IN     std_logic;
      DataOut   : OUT    LC3B_C_TAG
   );
   END COMPONENT;
   COMPONENT dirty_delay
   PORT (
      set_dirty     : IN     std_logic ;
      dirty_delayed : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BitArray USE ENTITY ece411.BitArray;
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : TagArray USE ENTITY ece411.TagArray;
   FOR ALL : dirty_delay USE ENTITY ece411.dirty_delay;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   --data is only invalid before
   --it is written to. set to
   --valid on every write
   
   write_valid <= way_write;
   valid <= way_write;                                       


   -- Instance port mappings.
   way_dirty : BitArray
      PORT MAP (
         Reset_L   => RESET_L,
         DataWrite => way_write,
         Index     => set_index,
         DataIn    => dirty_delayed,
         DataOut   => Dirty_out
      );
   way_valid : BitArray
      PORT MAP (
         Reset_L   => RESET_L,
         DataWrite => write_valid,
         Index     => set_index,
         DataIn    => valid,
         DataOut   => Valid_out
      );
   way_data : DataArray
      PORT MAP (
         Reset_L   => RESET_L,
         DataWrite => way_write,
         Index     => set_index,
         DataIn    => DataIn,
         DataOut   => Data_out
      );
   way_tag : TagArray
      PORT MAP (
         Reset_L   => RESET_L,
         DataWrite => way_write,
         Index     => set_index,
         DataIn    => tag,
         DataOut   => Tag_out
      );
   delay1ns : dirty_delay
      PORT MAP (
         set_dirty     => set_dirty,
         dirty_delayed => dirty_delayed
      );

END struct;
