-- VHDL Entity ece411.WRbyte_sel.generatedInstance
--
-- Created:
--          by - buris2.ews (gelib-057-26.ews.illinois.edu)
--          at - 22:01:54 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WRbyte_sel IS
   PORT( 
      ADDRESS2             : IN     lc3b_word;
      clk                  : IN     std_logic;
      MWRITEH_L            : OUT    std_logic;
      MWRITEL_L            : OUT    std_logic;
      SOME_SIGNAL_FROM_CW3 : IN     lc3b_word;
      Valid3out            : IN     std_logic
   );

END WRbyte_sel ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF WRbyte_sel IS 
BEGIN


END generatedInstance;
