-- VHDL Entity ece411.WRtoWord.symbol
--
-- Created:
--          by - buris2.ews (evrt-252-10.ews.illinois.edu)
--          at - 15:10:17 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WRtoWord IS
   PORT( 
      DATAOUT   : IN     LC3b_word;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      WR        : IN     std_logic;
      word_in   : IN     lc3b_word;
      Dout      : OUT    LC3b_word
   );

-- Declarations

END WRtoWord ;

--
-- VHDL Architecture ece411.WRtoWord.struct
--
-- Created:
--          by - buris2.ews (evrt-252-10.ews.illinois.edu)
--          at - 15:10:17 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF WRtoWord IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DinH  : lc3b_byte;
   SIGNAL DinL  : lc3b_byte;
   SIGNAL Hbyte : LC3b_byte;
   SIGNAL Lbyte : LC3b_byte;
   SIGNAL WH    : lc3b_byte;
   SIGNAL WL    : lc3b_byte;
   SIGNAL WRH   : std_logic;
   SIGNAL WRL   : std_logic;


   -- Component Declarations
   COMPONENT ANDINV2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      C : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT ByteJoin
   PORT (
      Hbyte : IN     LC3b_byte;
      Lbyte : IN     LC3b_byte;
      Dout  : OUT    LC3b_word
   );
   END COMPONENT;
   COMPONENT ByteMux2
   PORT (
      A   : IN     LC3b_byte ;
      B   : IN     LC3b_byte ;
      Sel : IN     std_logic ;
      F   : OUT    LC3b_byte 
   );
   END COMPONENT;
   COMPONENT wordsplit
   PORT (
      word_in : IN     lc3b_word ;
      byteH   : OUT    lc3b_byte ;
      byteL   : OUT    lc3b_byte 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ANDINV2 USE ENTITY ece411.ANDINV2;
   FOR ALL : ByteJoin USE ENTITY ece411.ByteJoin;
   FOR ALL : ByteMux2 USE ENTITY ece411.ByteMux2;
   FOR ALL : wordsplit USE ENTITY ece411.wordsplit;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   W_H : ANDINV2
      PORT MAP (
         A => WR,
         B => MWRITEH_L,
         C => WRH
      );
   W_L : ANDINV2
      PORT MAP (
         A => WR,
         B => MWRITEL_L,
         C => WRL
      );
   U_4 : ByteJoin
      PORT MAP (
         Hbyte => Hbyte,
         Lbyte => Lbyte,
         Dout  => Dout
      );
   HMUX : ByteMux2
      PORT MAP (
         A   => WH,
         B   => DinH,
         Sel => WRH,
         F   => Hbyte
      );
   LMUX : ByteMux2
      PORT MAP (
         A   => WL,
         B   => DinL,
         Sel => WRL,
         F   => Lbyte
      );
   U_2 : wordsplit
      PORT MAP (
         word_in => DATAOUT,
         byteH   => DinH,
         byteL   => DinL
      );
   U_3 : wordsplit
      PORT MAP (
         word_in => word_in,
         byteH   => WH,
         byteL   => WL
      );

END struct;
