echo "--- Executing initialization force file for ../testcode/mp22test3.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
force /start_h 0 @0
force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/mp22test3.asm program code."
run 5
change /mp2_cpu/dram/pdram/vhdl_memory/mem(0) X"0E"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(1) X"62"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(2) X"0F"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(3) X"64"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(4) X"10"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(5) X"66"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(6) X"40"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(7) X"68"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(8) X"80"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(9) X"6A"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(10) X"81"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(11) X"78"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(12) X"43"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(13) X"7A"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(14) X"40"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(15) X"6C"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(16) X"C0"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(17) X"6E"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(18) X"40"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(19) X"60"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(20) X"C0"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(21) X"60"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(22) X"81"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(23) X"64"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(24) X"43"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(25) X"66"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(26) X"FF"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(27) X"0F"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(28) X"40"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(29) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(30) X"C0"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(31) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(32) X"40"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(33) X"01"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(64) X"11"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(65) X"11"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(66) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(67) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(68) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(69) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(70) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(71) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(72) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(73) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(74) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(75) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(76) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(77) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(78) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(79) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(192) X"22"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(193) X"22"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(194) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(195) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(196) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(197) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(198) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(199) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(200) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(201) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(202) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(203) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(204) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(205) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(206) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(207) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(320) X"33"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(321) X"33"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(322) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(323) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(324) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(325) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(326) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(327) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(328) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(329) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(330) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(331) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(332) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(333) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(334) X"00"
change /mp2_cpu/dram/pdram/vhdl_memory/mem(335) X"00"
run 5
echo "Done loading ../testcode/mp22test3.asm program code."
